create table social_country (
       id bigint generated by default as identity,
        countryname varchar(255),
        code bigint,
        primary key (id)
    );

create table social_user_role (
       id bigint generated by default as identity,
        role varchar(255),
        user_a_id bigint,
        primary key (id)
    );
	
	 create table social_user_post (
       id bigint generated by default as identity,
        created_time timestamp(6),
        modified_time timestamp(6),
        post_data varchar(255),
        user_id bigint,
        primary key (id)
    );
	
	create table social_user_image (
       id bigint generated by default as identity,
        image varbinary(255),
        image_description varchar(255),
        image_name varchar(255),
        user_a_id bigint,
        primary key (id)
    );
	
	create table social_user (
       id bigint generated by default as identity,
        country varchar(255),
        create_date_time date,
        dob date,
        email varchar(255),
        first_name varchar(255),
        is_active boolean,
        last_name varchar(255),
        modified_date_time date,
        password varchar(255),
        profile_image varchar(255),
        primary key (id)
    );